### PR TITLE
PSRs

### PR DESCRIPTION
**Pull request by walter-garcia**
Add new PSR files
PSR-0 translated
Fixed some erros in PSR-1 file

### CODE REVIEW

**Comment by walter-garcia** [comment]
Fixed indent on PSR-1. Renamed PSR-2 and PSR-2-meta files. PSR-2-meta translated. Started PSR-2 translation

**Comment by jeanjar** [comment]
Remover todos os .DS_STORE q foram enviados.

**Comment by walter-garcia** [comment]
> Remover todos os .DS_STORE q foram enviados.

>>Already on .gitignore file.

**Comment by allythy** [comment]
:1st_place_medal:

**Pull request merged**
